### ISSUE TITLE
How to enable dark theme?

### ISSUE THREAD

**Issue by LumiteDubbz** [unc926/MacOSX_Gnome#1]
Hi,
I have selected this theme using the GNOME Tweak Tool, how do I now choose the dark mode. Thanks in advance.

**Comment by eab81070** [comment]
![dock](https://user-images.githubusercontent.com/10891369/40844876-111843f2-6583-11e8-86d1-8ad9f48f8fc0.png)

**Comment by unc926** [comment]
@LumiteDubbz 

 Set MacOS_DARK theme in Gnome-tweak-tool
